export const roastPrompts = [
  "Roast this annoying gym bro who never stops talking about protein shakes! 💪",
  "Roast someone who always says 'I'm not like other people' but is totally basic! 🙄", 
  "Roast that person who takes 50 selfies before posting one! 📸",
  "Roast someone who claims they're 'naturally funny' but tells the worst jokes! 😬",
  "Roast that friend who always shows up late but blames traffic! 🚗",
  "Roast the person who claps when the plane lands. ✈️👏",
  "Roast someone who still uses Internet Explorer in 2025. 🧓💻",
  "Roast that one friend who types 'u' instead of 'you' like it's 2009. 📱",
  "Roast the person who thinks pineapple pizza is a personality trait. 🍍🍕",
  "Roast someone who wears sunglasses indoors like a celebrity. 🕶️✨",
  "Roast the person who always says 'I could've been a model'. 💁‍♂️",
  "Roast someone who makes everything about their star sign. ♌✨",
  "Roast the guy who still dabs unironically. 🤦‍♂️",
  "Roast someone who quotes motivational Instagram posts like it's gospel. 📸🧠",
  "Roast the one who adds 'CEO of...' in their bio for everything. 🧢👨‍💼",
  "Roast someone who can't finish a sentence without saying 'literally'. 🙄",
  "Roast the person who always forgets your birthday but posts about their dog’s. 🐶🎂",
  "Roast the guy who thinks being 'alpha' means yelling louder. 🐺📢",
  "Roast someone who treats LinkedIn like a dating app. 💼💔",
  "Roast the person who calls themselves an entrepreneur for selling candy in 6th grade. 🍬📈",
  "Roast the one who uses 'work hard, play hard' as an excuse to be annoying. 🎉💼",
  "Roast the person who takes mirror selfies at the gym but lifts nothing. 🪞🏋️",
  "Roast someone who replies 'k' to heartfelt messages. 😐💔",
  "Roast the person who still says 'YOLO' like it's fresh. 😎🔥",
  "Roast the person who eats cereal with a fork. 🥣❓",
  "Roast the friend who keeps saying 'trust the process' but has no plan. 📉",
  "Roast someone who flexes crypto investments but lives with their mom. 🪙🏠",
  "Roast the one who sends 10 reels a day and gets mad if you don’t react. 📲😤",
  "Roast someone who says 'let that sink in' and never has a point. 🛁🧠",
  "Roast the person who vapes like they’re casting spells. 🧙‍♂️💨",
  "Roast someone who thinks 'main character energy' is an excuse to be rude. 🎬🙄",
  "Roast the guy who still calls people 'bro' in formal meetings. 🤝",
  "Roast someone who updates their status every 5 minutes. 📝⏰",
  "Roast the person who uses TikTok as their only news source. 📱🗞️",
  "Roast someone who drinks black coffee just to seem tough. ☕🖤",
  "Roast that friend who starts a new hustle every week and never finishes one. 💼🔁",
  "Roast the person who thinks loud = funny. 📢😐",
  "Roast someone who spends more time on Canva than actually working. 🎨⌛",
  "Roast that friend who turns every story into a motivational speech. 🗣️📈",
  "Roast someone who uses 'LOL' but never actually laughs. 😑",
  "Roast the guy who thinks wearing a beanie indoors is a personality. 🧢💭",
  "Roast someone who posts gym selfies after doing one push-up. 💪📸",
  "Roast the person who overuses filters and still says #NoFilter. 📷😂",
  "Roast someone who makes playlists called 'vibezzz'. 🎵😩",
  "Roast that person who 'can't function without coffee' but does nothing all day. ☕🛋️",
  "Roast the one who always has advice but never takes any. 🧠👂",
  "Roast someone who always asks 'Guess who?' like they’re a celebrity. 🙈❓",
  "Roast that friend who gatekeeps restaurants like it’s state secrets. 🍽️🔒",
  "Roast someone who says 'back in my day' but is 23. 🧓📅",
  "Roast the guy who tries to sell you NFTs at every party. 🧊📉",
  "Roast someone who treats WhatsApp group admin like a government role. 🗳️📱",
  "Roast the friend who watches one documentary and thinks they’re an expert. 🎥🧠",
  "Roast someone who wears crocs with socks and calls it fashion. 🧦🐊",
  "Roast the person who always says 'new year, new me' and stays the same. 🎆🔁",
  "Roast the guy who always talks about 'the grind' but naps all day. 🛏️💤",
  "Roast someone who thinks clapping at the end of a movie is mandatory. 👏🎬",
  "Roast the person who thinks 'I’m brutally honest' is a personality. 😐🔪",
  "Roast someone who puts ‘aspiring’ before everything. 💭🚫",
  "Roast the friend who believes their Spotify Wrapped defines them. 🎧🔮",
  "Roast someone who organizes their Google Calendar but not their life. 📅📉",
  "Roast the person who needs GPS to find their personality. 🗺️😶",
  "Roast someone who thinks wearing black = deep thinker. 🖤🧠",
  "Roast the guy who flexes his screen time like it’s a badge of honor. 📲📉",
  "Roast the person who still uses hashtags like #blessed #nofilter #vibes. 🧿📷",
  "Roast someone who says 'I’m just built different' but eats instant noodles every day. 🍜💪",
  "Roast the person who thinks their meme folder is a personality trait. 📂😬",
  "Roast someone who keeps tagging you in cringe reels. 📱🫠",
  "Roast that friend who thinks they’re mysterious just because they don’t reply. 🙄🕵️‍♂️",
  "Roast the person who uses 'CEO of ghosting' in their bio. 👻👔",
  "Roast someone who spends more time setting up their tripod than actually filming. 🎥⌛",
  "Roast the guy who talks about his 'brand' but doesn’t even have a website. 🖥️❌",
  "Roast the person who makes a big deal about 'cutting toxic people' every month. ✂️😤",
  "Roast someone who says 'trust me, bro' as their only source. 🧢🕵️‍♂️",
  "Roast that person who constantly posts 'I’m done explaining myself' but never stops talking. 🗣️🔁",
  "Roast the friend who edits their pics so much you don’t recognize them in real life. 🧑‍🎨🤷‍♀️",
  "Roast someone who thinks copying Elon tweets makes them a genius. 🚀🧠",
  "Roast that one guy who says 'crypto changed me' and now just tweets in all caps. 📉📣",
  "Roast the person who still quotes Vine like it’s current. 📼😩",
  "Roast the person who says ‘grindset’ but still lives off their parents. 🛏️💼",
  "Roast someone who uses 'main character syndrome' as an excuse to be toxic. 🎭😬",
  "Roast that person who thinks putting fairy lights in a room equals aesthetics. ✨🛏️",
  "Roast the friend who says 'I don’t need sleep, I need answers' but fails every exam. 💤❌",
  "Roast someone who owns a ring light but no ambition. 💡😑",
  "Roast the person who says 'sorry I’m late' like it’s a lifestyle. ⏰🚪",
  "Roast someone who thinks a cold shower and journaling solves everything. 🚿📓",
  "Roast the guy who only reads the first chapter of every self-help book. 📚🚫",
  "Roast someone who says 'this hit different' about everything. 🎯🙃",
  "Roast the person who still says 'that's what she said'. 🙄",
  "Roast someone who writes 'future millionaire' in their bio but borrows money for coffee. ☕💸",
  "Roast that friend who uses 7 emojis per sentence and still sounds boring. 😅🤣🔥💀😂🤷‍♂️🙌",
  "Roast the person who thinks being unavailable = mysterious. 📵🤐",
  "Roast someone who thinks owning a skateboard makes them deep. 🛹🧠",
  "Roast the friend who uses ChatGPT to flirt. 🤖💬❤️",
  "Roast someone who says 'don’t judge me' before doing the most judge-worthy thing. ⚖️😬",
  "Roast the person who thinks mood boards equal progress. 📌📉",
  "Roast the guy who wears cologne like it’s bug spray. 💨😷",
   "Roast this guy who still brags about his high school sports trophies. 🏆",
  "Roast someone who types in all caps thinking it makes their argument stronger. 🔊",
  "Roast that person who still uses 'YOLO' in 2025. 🙄",
  "Roast someone whose entire personality is coffee. ☕",
  "Roast that friend who can’t stop quoting The Office. 🧼",
  "Roast someone who wears sunglasses indoors. 🕶️",
  "Roast this person who thinks pineapple on pizza is a hot take. 🍍🍕",
  "Roast that friend who always says 'trust me, bro' as a source. 🕵️",
  "Roast someone who thinks using big words makes them smart. 🧠",
  "Roast this dude who still dabs unironically. 💀",
  "Roast that one guy who says 'I'm an alpha' but lives with his mom. 🐺",
  "Roast someone who sends voice notes instead of texts. 🎤",
  "Roast that friend who gives TED Talks in group chats. 🎤",
  "Roast this person who unironically says 'vibe check'. 📉",
  "Roast someone who posts gym selfies and skips leg day. 🏋️",
  "Roast that guy who thinks NFT is a personality. 📉",
  "Roast someone who uses 5-in-1 shampoo. 🚿",
  "Roast that friend who brings up astrology during arguments. 🔮",
  "Roast someone who thinks liking 'Friends' makes them quirky. 📺",
  "Roast that person who uses 'just saying' after every insult. 🙃",
  "Roast someone who overuses 'literally' and means none of it. 🤦",
  "Roast that guy who owns more crypto than common sense. 💰",
  "Roast someone who flexes their Spotify Wrapped like it's a PhD. 🎧",
  "Roast the person who takes 3 business days to reply, then says 'lol'. 🕒",
  "Roast that friend who thinks watching one documentary makes them an expert. 🎓",
  "Roast someone who always says 'I was just kidding' after being rude. 😬",
  "Roast the person who starts every sentence with 'as an empath'. 💧",
  "Roast someone who thinks sarcasm is a love language. 🖤",
  "Roast that person who says 'new year, new me'... every year. 🗓️",
  "Roast someone who claims they’re 'humbled' after flexing. 🤔",
  "Roast that one friend who disappears when the bill arrives. 💸",
  "Roast the person who edits selfies for 3 hours and still looks surprised. 📷",
  "Roast someone who talks about 'the grind' but naps 3 times a day. 😴",
  "Roast the dude who says 'sigma male' and gets no replies. 📉",
  "Roast someone who treats Twitter arguments like a full-time job. 🧑‍💻",
  "Roast the person who claps when the plane lands. 👏",
  "Roast someone who uses 50 hashtags on every post. #cringe",
  "Roast that friend who thinks 'read receipts off' is a power move. 📱",
  "Roast the person who says 'no offense' and then offends everyone. 😐",
  "Roast someone who has a ring light but no personality. 💡",
  "Roast that person whose entire diet is energy drinks. ⚡",
  "Roast someone who makes gym their religion... and protein powder their god. 🛐",
  "Roast that friend who overuses the fire emoji on every post. 🔥🔥🔥",
  "Roast the person who makes every conversation about themselves. 🪞",
  "Roast someone who brings PowerPoint energy to casual chats. 📊",
  "Roast the person who starts every sentence with 'Not to be rude, but...' 🚩",
  "Roast someone who lives by 'fake it till you make it' but forgot to make it. 🎭",
  "Roast the friend who thinks saying 'periodt' ends the debate. 🧃",
  "Roast someone who has more filters than followers. 📸",
  "Roast that person who thinks ‘sorry not sorry’ is a personality. 🙄",
  "Roast the one who wears a hoodie in 40°C like it’s a fashion statement. 🥵",
  "Roast someone who refuses to update their phone from 2015. 📱🪦",
  "Roast the person whose YouTube ads are more motivational than their life. 💼",
  "Roast the friend who starts 20 projects and finishes none. 📂",
  "Roast the person who uses LinkedIn like it's Instagram. 📸",
  "Roast the guy who calls himself a 'thought leader' with 12 followers. 🧠",
  "Roast the person who asks for 'Netflix recommendations' but watches the same show again. 📺",
  "Roast someone who says 'I was today years old' about basic facts. 📚",
  "Roast the friend who can’t take a joke but dishes them out daily. 🍽️",
  "Roast someone who adds 'CEO of' to their Twitter bio like it's a job. 🧢",
  "Roast the person who says 'it’s giving' for everything. 🧠❌",
  "Roast that guy who corrects everyone’s grammar but lives in his mom’s basement. 🏚️",
  "Roast someone who tags everyone in 'inspirational' posts. ✨",
  "Roast the friend who takes personality quizzes like they’re horoscopes. 🧩",
  "Roast the person who still forwards WhatsApp chain messages. 📨",
  "Roast someone who brags about waking up at 5AM and is useless all day. 🐓",
  "Roast the guy who thinks reposting quotes is emotional intelligence. 🧠",
  "Roast the friend who complains about drama but starts all of it. 🎭",
  "Roast the person who has 3 alarms and still oversleeps. ⏰",
  "Roast the one who thinks they’re mysterious but is just bad at communication. 🕵️‍♂️",
  "Roast someone whose idea of self-care is rewatching the same sad movie. 🎬",
  "Roast that guy who only reads book summaries but calls himself 'well-read'. 📖",
  "Roast the person who uses 'grindset' as an excuse to avoid friends. 📉",
  "Roast someone who says 'vintage' instead of admitting it’s just old. 🧥",
  "Roast the friend who gatekeeps music like it's state secrets. 🔐",
  "Roast the person who still says 'YOLO' in 2025. 🧟‍♂️",
  "Roast the guy who thinks crypto is still going to the moon. 🌝🚀",
  "Roast someone who flexes 'working remotely' from their couch. 🛋️",
  "Roast that one who acts rich on Instagram but split the bill 4 ways. 🍽️",
  "Roast someone who 'can’t live without coffee' but hasn’t lived since 2016. ☠️",
  "Roast the person who always says 'I'm so random!' but is predictable. 🔁",
  "Roast that guy who makes gym his entire personality. 🏋️‍♂️",
  "Roast the person who says 'I'm just being honest' before being mean. 🧂",
  "Roast someone who overuses AI but can’t pass a captcha. 🤖",
  "Roast the person who reads one self-help book and becomes a guru. 📚",
  "Roast someone who thinks 'introvert' means they can be rude. 🧊",
  "Roast that friend who always says 'I had a feeling'—after it's already happened. 🔮",
  "Roast the one who thinks flexing their sleep tracker is personality. ⌚",
  "Roast someone who thinks texting with punctuation is intimidating. 📱",
  "Roast the guy who still uses Vine references like it's 2014. 🍇",
  "Roast someone who buys gadgets they don’t use—except to show off. 📸",
  "Roast the friend who goes 'on a break' after every minor inconvenience. 🚨",
  "Roast someone whose iCloud is full but so is their drama. 🌩️",
  "Roast the person who opens 50 tabs and forgets all of them. 🧠💨"
];


export const getRandomPrompt = (): string => {Add commentMore actions
  const randomIndex = Math.floor(Math.random() * roastPrompts.length);
  return roastPrompts[randomIndex];
};